### ISSUE TITLE
Suggestion for author contributions

### ISSUE THREAD

**Issue by baoilleach** [linux4chemistry/linux4chemistry#1]
Currently, it reads "Linux4Chemistry was created by Nikodem Kuznik in 2001 and maintained by Noel O'Boyle between 2005 and 2013. The project is currently maintained by Gianluca Sforna and Riccardo Vianello."

I would change it to put your names first.

**Comment by rvianello** [comment]
Thanks for the suggestion, I rephrased that paragraph.
